version: '2'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      RABBITMQ_DEFAULT_VHOST: "/"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    environment:
      DEBUG: "${DEBUG}"
      MIGRATE: "${MIGRATE}"
      COLLECT_STATIC: "${COLLECT_STATIC}"
      SECRET_KEY: "${SECRET_KEY}"
      START_CELERY_WORKER: "${START_CELERY_WORKER}"
      CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
