version: '3'

services:
  nginx:
    image: nginx:1.15.8-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - statics:/var/www/static
      - media:/var/www/media
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"

  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      RABBITMQ_DEFAULT_VHOST: "/"
    restart: always
    ports:
      - "15672:15672"

  app:
    build: .
    environment:
      DEBUG: "${DEBUG}"
      MIGRATE: "${MIGRATE}"
      COLLECT_STATIC: "${COLLECT_STATIC}"
      BASE_URL: "${BASE_URL}"
      SECRET_KEY: "${SECRET_KEY}"
      START_CELERY_WORKER: "${START_CELERY_WORKER}"
      CELERY_BROKER_URL: "${CELERY_BROKER_URL}"
    volumes:
      - statics:/usr/src/app/static
      - media:/usr/src/app/media
    restart: always
    depends_on:
      - rabbitmq

volumes:
  statics:
  media:
