# Generated by Django 2.1.7 on 2019-02-17 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
        ('cars', '0001_initial'),
        ('numplates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numplate',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cars.Car'),
        ),
        migrations.AddField(
            model_name='numplate',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owners.Owner'),
        ),
    ]
